version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: schedule-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: SkiSchoolSchedule
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: